import { createContext, useContext, useEffect, useRef, useState, type ReactNode, type FormEvent } from 'react'
import { Brain, LogOut, Shield, Sparkles, X, Plus, Trash2, Loader2, Globe2, MessageSquareText } from 'lucide-react'
import { postJSON } from './api'
import './accounts.css'

type User = {id:string;email:string;name:string;role:'owner'|'member'}
type Session = {user:User|null;configured:boolean;clientId:string}
const AccountContext=createContext<{user:User;logout:()=>Promise<void>}|null>(null)
export function useAccount(){const context=useContext(AccountContext);if(!context)throw new Error('Sign-in required');return context}
export async function accountRequest<T>(resource:string,method='GET',data?:unknown):Promise<T>{
  const response=await fetch('/api/account?resource='+resource,{method,credentials:'same-origin',headers:{'content-type':'application/json','x-nomadjarvis':'1'},...(data===undefined?{}:{body:JSON.stringify(data)})})
  const result=await response.json().catch(()=>({error:'The server could not respond.'}))
  if(!response.ok){if(response.status===401 && !['session','google','nonce'].includes(resource))window.dispatchEvent(new Event('nomad-session-expired'));throw new Error(result.error||'Request failed.')}
  return result
}
type GoogleIdentity={initialize:(options:{client_id:string;nonce:string;callback:(result:{credential:string})=>void;auto_select:boolean})=>void;renderButton:(element:HTMLElement,options:{theme:string;size:string;width:number;text:string})=>void;disableAutoSelect:()=>void}
declare global {interface Window {google?:{accounts:{id:GoogleIdentity}}}}
let googleScript:Promise<void>|undefined
function loadGoogle(){
  if(window.google)return Promise.resolve()
  if(!googleScript)googleScript=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src='https://accounts.google.com/gsi/client';script.async=true;script.onload=()=>resolve();script.onerror=()=>{googleScript=undefined;script.remove();reject(new Error('Google sign-in could not load. Check your connection and reload.'))};document.head.appendChild(script)})
  return googleScript
}
export function AccountGate({children}:{children:ReactNode}){
  const [session,setSession]=useState<Session|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true)
  const check=async()=>{setLoading(true);setError('');try{setSession(await accountRequest<Session>('session'))}catch(e){setError((e as Error).message)}finally{setLoading(false)}}
  useEffect(()=>{void check();const expire=()=>{setSession(s=>s?{...s,user:null}:s);setError('Your session ended. Please sign in again.')};window.addEventListener('nomad-session-expired',expire);return()=>window.removeEventListener('nomad-session-expired',expire)},[])
  async function logout(){await accountRequest('logout','POST',{});window.google?.accounts.id.disableAutoSelect();setSession(s=>s?{...s,user:null}:s)}
  if(loading)return <div className="auth-page"><Loader2 className="spin" aria-label="Loading your workspace"/></div>
  if(session?.user)return <AccountContext.Provider key={session.user.id} value={{user:session.user,logout}}>{children}</AccountContext.Provider>
  return <div className="auth-page"><div className="auth-card"><div className="auth-brand"><span className="logo"><Sparkles size={22}/></span>NomadJarvis</div><span className="eyebrow">YOUR PRIVATE AI WORKSPACE</span><h1>A space that knows you.</h1><p>Your conversations, projects, and memories.<br/>One account. Your space.</p><div className="auth-divider"/>{session?.configured?<GoogleSignIn clientId={session.clientId} onSignedIn={user=>{setError('');setSession({...session,user})}}/>:<><p>Sign-in is being set up. Please check back soon.</p><button className="primary" onClick={()=>void check()}>Check again</button></>}{error&&<div role="alert" className="error">{error}</div>}<div className="auth-note"><Shield size={15}/> Invite-only. Sign in with the Google email the owner approved.</div><p><a href="/privacy.html">Privacy</a></p></div></div>
}
function GoogleSignIn({clientId,onSignedIn}:{clientId:string;onSignedIn:(user:User)=>void}){
  const button=useRef<HTMLDivElement>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0)
  useEffect(()=>{let active=true;void(async()=>{try{await loadGoogle();if(!active)return;const {nonce}=await accountRequest<{nonce:string}>('nonce','POST',{});if(!active||!button.current)return;window.google!.accounts.id.initialize({client_id:clientId,nonce,auto_select:false,callback:result=>{if(!active)return;setBusy(true);setError('');void accountRequest<{user:User}>('google','POST',{credential:result.credential}).then(r=>{if(active)onSignedIn(r.user)}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)})}});button.current.replaceChildren();window.google!.accounts.id.renderButton(button.current,{theme:'outline',size:'large',width:280,text:'signin_with'})}catch(e){if(active)setError((e as Error).message)}})();return()=>{active=false}},[clientId,attempt])
  return <div className="google-signin"><div ref={button} style={{display:busy?'none':'flex'}}/>{busy&&<span><Loader2 className="spin" size={18}/> Opening your space…</span>}{error&&<><p role="alert" className="error">{error}</p><button className="quiet-button" onClick={()=>{setError('');setAttempt(v=>v+1)}}>Try again</button></>}</div>
}
export function AccountMenu(){
  const {user,logout}=useAccount(),[panel,setPanel]=useState<'memories'|'access'|null>(null),[error,setError]=useState('')
  return <><div className="account-menu"><button className="nav" title="My memories" onClick={()=>setPanel('memories')}><Brain size={18}/><span>My memories</span></button>{user.role==='owner'&&<button className="nav" title="Manage access" onClick={()=>setPanel('access')}><Shield size={18}/><span>Manage access</span></button>}<div className="account-identity"><div className="avatar">{user.name.slice(0,1).toUpperCase()}</div><div><b>{user.name}</b><small>{user.email}</small></div></div><button className="nav" title="Sign out" onClick={()=>void logout().catch(e=>setError(e.message))}><LogOut size={18}/><span>Sign out</span></button>{error&&<p className="error">{error}</p>}</div>{panel&&<div className="modal-backdrop" onClick={()=>setPanel(null)}><section className="account-dialog" role="dialog" aria-modal="true" aria-label={panel==='memories'?'My memories':'Manage access'} onClick={e=>e.stopPropagation()} onKeyDown={e=>{if(e.key==='Escape')setPanel(null)}}><div className="dialog-heading"><h2>{panel==='memories'?'My memories':'Manage access'}</h2><button autoFocus className="icon-button" aria-label="Close" onClick={()=>setPanel(null)}><X size={20}/></button></div>{panel==='memories'?<Memories/>:<Access/>}</section></div>}</>
}
function Memories(){
  const [items,setItems]=useState<{id:string;content:string}[]>([]),[content,setContent]=useState(''),[editing,setEditing]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const load=async()=>setItems((await accountRequest<{memories:typeof items}>('memories')).memories)
  useEffect(()=>{void load().catch(e=>setError(e.message))},[])
  async function save(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{await accountRequest('memories',editing?'PUT':'POST',{content,...(editing?{id:editing}:{})});setContent('');setEditing(null);await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function remove(id:string){setBusy(true);setError('');try{await accountRequest('memories','DELETE',{id});if(editing===id){setEditing(null);setContent('')}await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <><p className="panel-copy">Things you want Jarvis to remember about you. These are private to your account and included in your future chats. Nothing is saved here automatically.</p><form onSubmit={save}><label htmlFor="memory-text">{editing?'Edit memory':'Add a memory'}</label><textarea id="memory-text" maxLength={2000} className="account-input" value={content} onChange={e=>setContent(e.target.value)} placeholder="For example: I prefer concise answers and work in Bangkok."/><div className="row"><small>{content.length}/2000</small><div>{editing&&<button type="button" className="quiet-button" onClick={()=>{setEditing(null);setContent('')}}>Cancel</button>}<button className="primary" disabled={busy||!content.trim()}>{editing?'Save changes':'Save memory'}</button></div></div></form>{error&&<p role="alert" className="error">{error}</p>}<div className="account-list">{!items.length&&<p className="panel-copy">No memories yet.</p>}{items.map(item=><article key={item.id}><p>{item.content}</p><div><button className="quiet-button" disabled={busy} onClick={()=>{setEditing(item.id);setContent(item.content)}}>Edit</button><button className="quiet-button danger" disabled={busy} onClick={()=>void remove(item.id)}>Delete</button></div></article>)}</div></>
}
function Access(){
  const {user}=useAccount(),[items,setItems]=useState<{email:string;name?:string}[]>([]),[email,setEmail]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
  const load=async()=>setItems((await accountRequest<{invites:typeof items}>('invites')).invites)
  useEffect(()=>{void load().catch(e=>setError(e.message))},[])
  async function change(method:string,address:string){setBusy(true);setError('');setNotice('');try{await accountRequest('invites',method,{email:address});setEmail('');await load();setNotice(method==='POST'?'Access added. Share this site’s link with them; no email was sent.':'Access revoked. Their active sessions have ended.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <><p className="panel-copy">Only Google accounts on this list can enter. Each person has their own private workspace. You manage access; members’ conversations and memories aren’t shown here.</p><div className="owner-badge">Owner: {user.email}</div><form onSubmit={e=>{e.preventDefault();void change('POST',email)}}><label htmlFor="invite-email">Google email address</label><div className="invite-row"><input id="invite-email" type="email" required maxLength={254} className="account-input" value={email} onChange={e=>setEmail(e.target.value)} placeholder="name@gmail.com"/><button className="primary" disabled={busy||!email.trim()}>Allow access</button></div></form>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="success-note">{notice}</p>}<div className="account-list">{!items.length&&<p className="panel-copy">You haven’t invited anyone yet.</p>}{items.map(item=><article key={item.email}><div><b>{item.email}</b><small>{item.name?'Has signed in':'Invitation ready'}</small></div><button className="quiet-button danger" disabled={busy} onClick={()=>void change('DELETE',item.email)}>Revoke access</button></article>)}</div></>
}
type ChatMessage={role:'user'|'assistant';content:string}
type Conversation={id:string;title:string}
export function PrivateChat(){
  const {user}=useAccount(),[conversations,setConversations]=useState<Conversation[]>([]),[id,setId]=useState<string|null>(null),[messages,setMessages]=useState<ChatMessage[]>([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[web,setWeb]=useState(true),[error,setError]=useState('')
  const lock=useRef(false),stream=useRef<HTMLDivElement>(null)
  const refresh=async()=>setConversations((await accountRequest<{conversations:Conversation[]}>('conversations')).conversations)
  useEffect(()=>{void refresh().catch(e=>setError(e.message));const reset=()=>{if(!lock.current){setId(null);setMessages([]);setError('')}};window.addEventListener('nomad-new-chat',reset);return()=>window.removeEventListener('nomad-new-chat',reset)},[])
  useEffect(()=>{stream.current?.scrollTo({top:stream.current.scrollHeight})},[messages,busy])
  async function open(next:string){if(lock.current)return;lock.current=true;setLoading(true);setError('');try{const data=await accountRequest<{messages:ChatMessage[]}>('conversations&id='+encodeURIComponent(next));setId(next);setMessages(data.messages)}catch(e){setError((e as Error).message)}finally{lock.current=false;setLoading(false)}}
  async function remove(){if(!id||lock.current)return;lock.current=true;setLoading(true);try{await accountRequest('conversations','DELETE',{id});setId(null);setMessages([]);await refresh()}catch(e){setError((e as Error).message)}finally{lock.current=false;setLoading(false)}}
  async function submit(e:FormEvent){e.preventDefault();if(!input.trim()||lock.current)return;lock.current=true;setBusy(true);setError('');const question=input.trim();try{const result=await postJSON<{answer:string;conversationId:string}>('/api/chat',{message:question,useWeb:web,conversationId:id});setId(result.conversationId);setMessages(m=>[...m,{role:'user',content:question},{role:'assistant',content:result.answer}]);setInput('');await refresh()}catch(e){setError((e as Error).message)}finally{lock.current=false;setBusy(false)}}
  return <section className="workspace chat"><div className="conversation-bar"><MessageSquareText size={17}/><select aria-label="Saved conversations" value={id||''} disabled={busy||loading} onChange={e=>{if(e.target.value)void open(e.target.value);else{setId(null);setMessages([]);setError('')}}}><option value="">New conversation</option>{conversations.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button className="icon-button" aria-label="New conversation" disabled={busy||loading} onClick={()=>{setId(null);setMessages([]);setError('')}}><Plus size={18}/></button>{id&&<button className="icon-button" aria-label="Delete this conversation" disabled={busy||loading} onClick={()=>void remove()}><Trash2 size={16}/></button>}</div><div className="chat-stream" ref={stream}>{!messages.length&&!loading&&<div className="welcome"><div className="big-orb"><Sparkles size={30}/></div><h2>Your space, {user.name.split(' ')[0]}.</h2><p>Pick up a conversation or start something new.<br/>Jarvis uses the memories you choose to save.</p></div>}{loading&&<Loader2 className="spin" aria-label="Loading conversation"/>}{messages.map((m,i)=><div className={'bubble '+m.role} key={i}>{m.content}</div>)}{busy&&<div className="bubble assistant loading"><Loader2 className="spin" size={16}/> Thinking…</div>}{error&&<div className="error" role="alert">{error}</div>}</div><form className="composer" onSubmit={submit}><textarea aria-label="Message" maxLength={12000} disabled={busy||loading} value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask NomadJarvis anything…" onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();e.currentTarget.form?.requestSubmit()}}}/><div className="composer-footer"><button type="button" className={'tool '+(web?'selected':'')} onClick={()=>setWeb(v=>!v)}><Globe2 size={16}/>Web {web?'on':'off'}</button><button className="send" disabled={busy||loading||!input.trim()}>Send</button></div></form></section>
}
